### ISSUE TITLE
unknown protoo notification.method "downlinkBwe  

### ISSUE THREAD

**Issue by olzii** [stasoft91/mediasoup-nuxt-demo#6]
Hi friend,

I tried to run your MediasoupNuxt client app, it did not display remote participant's video and says that error when new user connected.

ERROR : unknown protoo notification.method "downlinkBwe  
| eval | @ | RoomClient.js?220c:693 
  | emit | @ | events.js?faa1:152
  | safeEmit | @ | EnhancedEventEmitter.js?eb2e:18
  | _handleNotification | @ | Peer.js?a767:342
  | eval | @ | Peer.js?a767:267
  | emit | @ | events.js?faa1:152
  | safeEmit | @ | EnhancedEventEmitter.js?eb2e:18
  | _ws.onmessage | @ | WebSocketTransport.js?e20c:206

![image](https://user-images.githubusercontent.com/5012289/103408684-7b457e80-4b9e-11eb-8724-70be94e16317.png)

![image](https://user-images.githubusercontent.com/5012289/103408439-6f0cf180-4b9d-11eb-92c6-ce725137fb76.png)

Do you have any suggestion ? How to correct it ?

**Comment by stasoft91** [comment]
Kek, in fact I didn`t manage to even run it to see 'Connected' green light, so I, um, guess either the code is rotten with some dependencies, or you configured it wrong :\

**Comment by stasoft91** [comment]
Also you could try my other two repos about mediasoup in Vue
https://github.com/zeye-ru

**Comment by olzii** [comment]
I need to run this Nuxt code, because my main project is based on Nuxt.js. So i want to add video chat feature on my main project.

I changed following changes in urlFactory.js file. You could run and see error. If you have time, please help me
```
let protooPort = 4443

if (window.location.hostname === 'test.mediasoup.org') protooPort = 4444

export function getProtooUrl({ roomId, peerId, forceH264, forceVP9 }) {
  const hostname = 'mediasoup.oyuntan.mn' // window.location.hostname
  let url = `wss://${hostname}:${protooPort}/?roomId=${roomId}&peerId=${peerId}`

  if (forceH264) url = `${url}&forceH264=true`
  else if (forceVP9) url = `${url}&forceVP9=true`

  return url
}
```

**Comment by olzii** [comment]
I have resolved remote participant's video issue. It was firewall issue and now it is ok. 

But DOWNLINKBWE error is not corrected. It shows every seconds. Do you have any idea about this error ?

**Comment by stasoft91** [comment]
Well, I can only advise you to check if error is present in official mediasoup demo. If it is you should ask them (though I advise you to not, because it is a demo, and dudes aren`t really interested in fixing it).
So in the end you only solution to use mediasoup in your app is to learn it the hard way through extensive documentation reading. Let me repeat it - this is just a simple buggy port of simple and buggy demo, i wouldn`t expect much of it =)
